### ISSUE TITLE
Activities Lost

### ISSUE THREAD

**Issue by PhilippParis** [TobsF/snaptracker#3]
### Problem Description
All previously tracked activities of the current month are lost after reopening SnapTracker.

### Possible Causes
SnapTracker was killed due to a forced shutdown by the windows update, maybe that caused a glitch to persist the activities.json with empty values?

[06-2024-activities.json](https://github.com/user-attachments/files/16024959/06-2024-activities.json)

**Comment by TobsF** [comment]
I'd assume this might occur when Snaptracker is forcefully shut down during saving.

Will look into this.

**Comment by TobsF** [comment]
This should be resolved on main and will be included in the next release.
